services:
  - type: web
    name: getreferencia
    env: node
    plan: free
    buildCommand: bash -c "npm install && npx playwright install --with-deps"
    startCommand: node server.js
    autoDeploy: true
